# Generated by Django 4.2.7 on 2023-12-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('set_number', models.IntegerField()),
                ('weight', models.FloatField()),
                ('reps', models.IntegerField()),
            ],
        ),
    ]
